### ISSUE TITLE
Not able to retrieve the Lightning Web Component from non-scratch org like sandbox or developer org

### ISSUE THREAD

**Issue by nirdeshk1988** [forcedotcom/cli-packages#33]
### Summary

Not able to retrieve the Lightning Web Component from non-scratch org like sandbox or developer org. I have created the LWC and deploy in sandbox but now i am not able to retrieve. While running the command it is giving the error 'ERROR:  Cannot read property 'fileName' of undefined.'

### Steps To Reproduce:

1.  Create the LWC and deploy in sandbox or developer org.
1.  This is step 2. Now try to retrieve the LWC either VS code GUI or CLI below command 
sfdx force:source:retrieve -m LightningComponentBundle

### Expected result

LWC should be retrieve .

### Actual result

It is giving the error 'Cannot read property 'fileName' of undefined.'

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by shetzel** [comment]
The rest of the template is important to fill out, particularly in this case, however this is not the proper place to report this issue since it has nothing to do with the code in this repo.
This bug was fixed in updated server and salesforcedx plugin releases.  You must be on the latest pre-release version of the CLI plugin, and your org must have the latest 218 patch updates.  If both of those things are true, then this is an investigation for the SFDX CLI team.
